name: Push builds

on:
  push:
    branches:
      - main

jobs:
  build-web:
    uses: Srynetix/godot-github-workflows/.github/workflows/build-game-3.5.yml@main
    with:
      platform: HTML5
      name: bombertest
      output_name: index.html
  build-windows:
    uses: Srynetix/godot-github-workflows/.github/workflows/build-game-3.5.yml@main
    with:
      platform: Windows Desktop
      name: bombertest
      output_name: Bombertest.exe